### ISSUE TITLE
Make the program work also if user enters an unknown term

### ISSUE THREAD

**Issue by saanahyttinen** [kanerv/TuukkaSaanaKanerva#10]
3. If you just copy the code from the tutorial, your program will crash if you enter a word (term) that does not occur in any document in the collection. Modify your program to work correctly also in the case that a term is unknown. For instance, what documents should be retrieved for a search such as: (1) "unknownweirdword", (2) "NOT unknownweirdword", or (3) "unknownweirdword OR this"?  (If this is too difficult, don't get stuck here, but come back to it later.)

**Comment by TuukkaOT** [comment]
I added a try-exception in case the term isn't found in the list and now the app can handle wrong terms:
try:
            hits_matrix = eval(rewrite_query(query))
            hits_list = list(hits_matrix.nonzero()[1])
            for i, doc_idx in enumerate(hits_list):
                print("Matching doc #{:d}: {:s}".format(i, documents[doc_idx]))
                print()

        except KeyError:
            print("Search term not found. No Matching doc.")

**Comment by TuukkaOT** [comment]
Closing these, please open if you find the steps not working on your end.
