### ISSUE TITLE
Index all words that didn't work originally

### ISSUE THREAD

**Issue by saanahyttinen** [kanerv/TuukkaSaanaKanerva#11]
4. Have you noticed that not all words in the toy data were actually indexed by the code in the tutorial? Which ones? Would you like to index all words containing alpha-numerical characters? Can you solve that? The answer can be found here: https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html  (Again, don't waste time on this one if it is too difficult, but return to it later.)

**Comment by TuukkaOT** [comment]
I added the regular expression r'(?u)\b\w+\b', i.e., I deleted the extra "\w" from sklearn's default tokenizer that requires two alphanumerical characters for tokens. Now it sees things like "a", as terms.
