### ISSUE TITLE
Limit the amount of articles printed and/or only print first <i>n</i> number of words or characters.

### ISSUE THREAD

**Issue by TuukkaOT** [kanerv/TuukkaSaanaKanerva#14]
Now the app prints all the articles fully which makes it a little difficult to operate. Perhaps we should only print, e.g., the first 20 words and 20 articles?

**Comment by TuukkaOT** [comment]
I changed the code so that it prints only the first 10 findings, but I wasn't able to make it only print a part of the actual article. Maybe someone else knows how to do that?

**Comment by TuukkaOT** [comment]
Now I managed to truncate the length of the print. It took me a while to realise it was super simple. Just changed the .format() to include only 1000 characters.

**Comment by kanerv** [comment]
The instruction (copied in our issue #9) did suggest just printing just the first x characters/words of the document if the content of the documents were long. I agree that it would make sense to print the part of the text where the search term(s) actually appear, but I don't think we are expected to know how to do it yet. :)

**Comment by TuukkaOT** [comment]
Yeh true. That would be cool though. btw, can you try with the finnish wikipedia dump, if the program can handle it with your computer without freezing? You have to first take out the "if len(teksti) < 100000:" part for it to go through the whole file. I put it there to protect my crap laptop :D

**Comment by kanerv** [comment]
Oh yeah, I was wondering what that line was for 😄 

I'll try the Finnish Wikipedia next!

**Comment by TuukkaOT** [comment]
I added a progress bar so there may be problems with merging if you have pulled the files before that. I only made changes between lines 2, 3, and 22-36, i.e. importing and reading the file.
