### ISSUE TITLE
Edit the app so it can deal with big files better.

### ISSUE THREAD

**Issue by TuukkaOT** [kanerv/TuukkaSaanaKanerva#15]
Right now my computer crashes when I try to use the whole Finnish wikipedia dump. Can we fix this?

**Comment by kanerv** [comment]
<strike>OMG! I tried to do searches again with the Finnish Wikipedia corpus and it works!! I've no idea why it crashed last time, but who cares, since our program works!! 🎉  </strike>  **edit:** Nevermind, it did not work....

Btw, the progress bar was a great addition 💯
