### ISSUE TITLE
Program crashing when searching with NOT

### ISSUE THREAD

**Issue by saanahyttinen** [kanerv/TuukkaSaanaKanerva#17]
I tested the program hakukone.py and it now seems to crash when using 'NOT' as a parameter. Does this happen for others? I will try to see what is the problem here.
Otherwise the program seems to work perfectly!

**Comment by saanahyttinen** [comment]
This is the error message I get:

Enter a search term: that NOT phone
Query: 'that not phone'
Traceback (most recent call last):
  File "hakukone.py", line 113, in <module>
    main()
  File "hakukone.py", line 105, in main
    test_query(query)
  File "hakukone.py", line 72, in test_query
    hits_matrix = eval(rewrite_query(query))
  File "<string>", line 1
    sparse_td_matrix[t2i["that"]].todense() 1 - sparse_td_matrix[t2i["phone"]].todense()
                                            ^
SyntaxError: invalid syntax

**Comment by TuukkaOT** [comment]
I think the reason is that "that NOT phone" isn't a valid search. It should be "that AND NOT phone" or "NOT phone AND that". We should make it give a proper error message though without crashing :)
EDIT: Do you wanna try a regex for it? I can also do it if you don't have time.

**Comment by saanahyttinen** [comment]
Whoopsie you're right, sorry! An error message is a good idea though, I can try to do that!

**Comment by saanahyttinen** [comment]
Took a while to remember to use re.match but now the error message is added! :)
