### ISSUE TITLE
Make the program print precisely the header of the article, as opposed to n first characters.

### ISSUE THREAD

**Issue by TuukkaOT** [kanerv/TuukkaSaanaKanerva#22]
Right now the app prints first 15 characters from the document without the xml markup, and then 50 characters snippet of the occurrence of the term in the document. Problem is that the headers are different length so some times you get stuff like: "Animal Anim" Instead of just Animal.

**Comment by kanerv** [comment]
I used the .split('"') method to retrieve the header for printing. The snippet does not work yet.
