### ISSUE TITLE
Fix the snippet for relevance search

### ISSUE THREAD

**Issue by TuukkaOT** [kanerv/TuukkaSaanaKanerva#23]
Printing the preview with the stem searcher works, but with relevance.py it doesn't work with all search terms. It works with "anarchism" but not "amsterdam", for example. I dont have time now to look into it and fix it.

**Comment by kanerv** [comment]
I fixed it! The -find() function is case sensitive and that's why it could not retrieve amsterdam, since cities are normally written with capital letters. 😆 Now the program prints a snippet which is 20 characters before the search term and 40 characters after 👍

**Comment by TuukkaOT** [comment]
Nice, this looks really good! The only problem is that it doesn't print a snippet in case the document starts with the term. E.g. "anarchism" which starts with "anarchism is a....".
EDIT: I think the problem is the "[snippet_index-20:" part so it doesn't print if there is not anything on that index in the document. Maybe we can just print it from the snippet_index onwards?

**Comment by kanerv** [comment]
oh, I see! I think an if clause could fix that. Or just make it simple as you suggested and just print from the snippet onwards
