### ISSUE TITLE
Add the stemmer search into the relevance search engine and make the results full words instead of stems.

### ISSUE THREAD

**Issue by TuukkaOT** [kanerv/TuukkaSaanaKanerva#24]
So I looked at some of the other teams' search engines and at least one had managed to make the stem search in the relevance search program, so that when you search, e.g., hous, you get results that actually show the original text with full words. To be honest this is testing the limits of my skills and I don't have much more time this week, so I'm not sure if I'm able to contribute much.

**Comment by TuukkaOT** [comment]
My best guess for doing this is something on the lines of putting the code from the stem search into a function in the relevance search, and making another term-dictionary matrix, "stem_documents" list etc. Then come printing time, use the index from the stem search list but print from the original "documents" list. so basically, if there is a "hous_s" on 31, 51, 120 in the "stem_documents" list, print from those same list indexes from the "documents".

**Comment by saanahyttinen** [comment]
Made the stemmer as part of the relevance search engine at #19 ! It's now in a stem() -function.

**Comment by saanahyttinen** [comment]
I noticed that the program now works well until the first stem search, but after that it looks like it's using the stemmed documents also when searching for exact matches. Unfortunately I don't think I have time to try to solve this today but if anyone does I just wanted to let you know.

**Comment by TuukkaOT** [comment]
Good that you noticed this! I fixed it now by making a function for relevance search documents. I also changed so that the stem function also uses the "documents_in" parametre given to it instead of the text_string from outside for clarity.

**Comment by saanahyttinen** [comment]
Great, thank you!

**Comment by kanerv** [comment]
> My best guess for doing this is something on the lines of putting the code from the stem search into a function in the relevance search, and making another term-dictionary matrix, "stem_documents" list etc. Then come printing time, use the index from the stem search list but print from the original "documents" list. so basically, if there is a "hous_s" on 31, 51, 120 in the "stem_documents" list, print from those same list indexes from the "documents".

I tried to fix the printing in the stem search. However, the indexing of stemmed documents does not match with the unstemmed documents, since the stemming process adds characters... The additional print line is currently commented out, but if you want to experiment, you can find it inside the test_query(query) function in relevance.py.
