### ISSUE TITLE
fix stem search in new app

### ISSUE THREAD

**Issue by TuukkaOT** [kanerv/TuukkaSaanaKanerva#28]

**Comment by TuukkaOT** [comment]
I tried this and the wildcard but dont have time to make it work now. I think the problem is that the type of the form in the index.html file is "text", so it does not take characters like _ and *. I think it would work if we make e.g. a drop down menu for user to choose if they want exact match search, stem or wildcard. If the user chooses exact match the name of the text box should be query_e, if they want stem, then the name could be query_s and if wildcard, then query_w. In the python file we would need to change "if query:" and delete the regular expressions from the loop:

if query_e: documents = relevance(text.... 

elif query_s: prin("searching a stem")....

elif query_w: documents = relevance(text_string)
            queries = []

**Comment by TuukkaOT** [comment]
I got this far but my skills in whatever html javascript etc. are zero so I wasn't able to make it work yet.
![image](https://user-images.githubusercontent.com/77778762/107739529-c14f3f80-6d11-11eb-9cc0-b4001c28030e.png)

**Comment by TuukkaOT** [comment]
So I managed to get an option for different searches, but still the stem search doesn't work and wildcard only works if there aren't hyphenated words containing that word, e.g. thei* works but not anarch*. I think we need to tweak the regex in the wildcard option. With the stem I'm not sure.

**Comment by TuukkaOT** [comment]
I fixed the stem search. Now the search works without the _s, e.g. anarch, but it still prints it as anarch_s. Problem was that the function "stem()" outputted a list called documents_out instead of documents.

**Comment by saanahyttinen** [comment]
Great job, thanks!

I noticed an interesting thing though: when doing an exact search for 'aruba' the program gives matches in the article 'Aruba' BUT ALSO in the stemmed version 'aruba_s'!
Not sure how this happens or if the same thing happens with other words. I was wondering if the reason could be that the word is both an actual word and a stem, but since we choose the option to do stem search separately this sould not make a difference. At least 'amsterdam' works fine so that exact search returns exact matches and stem search stemmed matches.

**Comment by saanahyttinen** [comment]
The 'aruba' search seems to be working now so never mind!

**Comment by kanerv** [comment]
> Great job, thanks!
> 
> I noticed an interesting thing though: when doing an exact search for 'aruba' the program gives matches in the article 'Aruba' BUT ALSO in the stemmed version 'aruba_s'!
> Not sure how this happens or if the same thing happens with other words. I was wondering if the reason could be that the word is both an actual word and a stem, but since we choose the option to do stem search separately this sould not make a difference. At least 'amsterdam' works fine so that exact search returns exact matches and stem search stemmed matches.

This just happened to me when I did a stem search and then a wildcard search right after... I think we need to initialize/clear our variables more carefully.

**Comment by TuukkaOT** [comment]
Yeh I was just thinking if the reason is that relevance() and stem() both append to documents instead of returning documents_out. Problem is that when I changed that, it says empty vocabulary, and I wasn't able to fix it  yet at least.

**Comment by kanerv** [comment]
There should no longer be double printing issues. I added a line that overwrites the documents variable before stem() or relevance() functions are called. **EDIT: I got excited too soon.... I did some further testing and my changes didn't work after all. I'm really not sure  how to fix this**  😢 

(Also did some documenting and realized there was an unnecessary block of code in the test_query(query) function. 😅 I commented it out.)

**Comment by TuukkaOT** [comment]
Okay so it works now. What I did was that I changed the documents variable into documents_s in the stem function so documents is appended only from relevance function. I made "choice" and "documents_s" global and added an if-clause in the test_query(), "if choice == stem: documents = documents_s".

**Comment by TuukkaOT** [comment]
I also got the stem search to print full words, the only problem is that the snippet is a little off in some articles. I don't know why yet but I think we can figure it out. If not we can go back to the crappy printing.
