### ISSUE TITLE
Print something if no matches are found

### ISSUE THREAD

**Issue by saanahyttinen** [kanerv/TuukkaSaanaKanerva#32]

**Comment by saanahyttinen** [comment]
At the moment, if the search word doesn't match anything in the documents, the exact and stem searches crash, and the wildcard search just returns to a new search.

**Comment by saanahyttinen** [comment]
I tried to make the program output 'No matching documents found' by adding if-clause (row 125):
if len(ranked_scores_and_doc_ids) == 0:
.......

But this does not work yet. Unfortunately I don't have more time to work on this right now.

**Comment by kanerv** [comment]
@TuukkaOT, are you sure we want to keep quotation marks and full stops? I mean here:

`token_pattern=r"\b\w\w+\-*\'*\.*\"*\w*\b"`

I mean if I search for _house_, I want it to match _"house"_ and _house._, but now they are distinguished in the tokenization and won't therefore match in the search. If I understood this correctly 😅

**Comment by kanerv** [comment]
<img width="1440" alt="Screenshot 2021-02-15 at 20 59 14" src="https://user-images.githubusercontent.com/77584213/107984542-ce4d8680-6fd0-11eb-9c61-a143875de51a.png">

I don't know if this issue is related.... my brain is way too tired already. I searched for _cat_ and somehow it matched _cation_ 😹

**Comment by kanerv** [comment]
I think I fixed this! The program now tests if the query matches the terms retrieved from the data. If not, _matches_ only consist of a line "term not found"

**Comment by kanerv** [comment]
SORRY this broke the stem search! I'll look into it
