### ISSUE TITLE
fix exact search

### ISSUE THREAD

**Issue by kanerv** [kanerv/TuukkaSaanaKanerva#33]
<img width="1440" alt="Screenshot 2021-02-15 at 20 59 14" src="https://user-images.githubusercontent.com/77584213/107984542-ce4d8680-6fd0-11eb-9c61-a143875de51a.png">

I don't know if this issue is related.... my brain is way too tired already. I searched for _cat_ and somehow it matched _cation_ 😹

_Originally posted by @kanerv in https://github.com/kanerv/TuukkaSaanaKanerva/issues/32#issuecomment-779403323_

This is still an issue 🐱

**Comment by saanahyttinen** [comment]
I think this happens because the article actually does contain the word 'cat', but the snippet prints the first time a word in the article includes 'cat', which here is publiCATion. So the search works but the snippet printing shows a wrong part of the article...

**Comment by saanahyttinen** [comment]
I guess this is dependant on the .find() function in line 130 
snippet_index = documents[i].lower().find(query)
so I'm not sure how we could fix this.

**Comment by TuukkaOT** [comment]
I tried to fix this with a regex, something like "\b"+query so it has to start at a word boundary but didn't get it to work. I have to work on another course today so I dont have time to make it work :/

**Comment by saanahyttinen** [comment]
I'm just trying to do something similar :D let's see if i manage to get it work!

**Comment by kanerv** [comment]
> I think this happens because the article actually does contain the word 'cat', but the snippet prints the first time a word in the article includes 'cat', which here is publiCATion. So the search works but the snippet printing shows a wrong part of the article...

Well to me alteast this is good news because for a moment I was worried our search function is broken! 😅

**Comment by saanahyttinen** [comment]
Managed to fix the snippet printing so that it starts from the first exact match! I had to use start() to find the index instead of find() so I commented out the original way.

**Comment by kanerv** [comment]
Yay! Great work Saana! 🎉  I think it's ok to just delete old code when it's no longer needed. There is always the possibility to access previous versions/commits form GitHub ✌️
