### ISSUE TITLE
[S] Study Spacy modules and create a plan for a plot implementation

### ISSUE THREAD

**Issue by kanerv** [kanerv/TuukkaSaanaKanerva#41]
We need to figure out what kind of information we want to present in the plots and make a plan for it. I hope this will become clearer as we get more familiar with our data.

**Comment by TuukkaOT** [comment]
I realised the themes are not just words that are frequently used but often they're more like concepts, e.g. "powerhouse performance", "engrossing story", "fantastic woman", "black man". There seems to be quite a few different things that can be done with PKE. Maybe we should try out different types of extractors and see what we can find out from our data.

**Comment by kanerv** [comment]
I tried working with spacy and managed to create bar plots for adjectives and verbs appearing in the critic's consensus matching the search query. However, these aren't that interesting after all, since there are very few repeated words...

I also tried named entity recognition, but wasn't able to get it to work. So I left it out from the code I added.
