### ISSUE TITLE
Server crashing when using the new hakukone.py

### ISSUE THREAD

**Issue by saanahyttinen** [kanerv/TuukkaSaanaKanerva#42]
It seems like my server crashes every time I try to search a word with our new app (week_5 hakukone.py). My python just quits unexpectedly and I have to get the server running again after every search. Does anyone else have this problem?

**Comment by saanahyttinen** [comment]
I did small changes to the hakukone.py app and index according to Raul's example's bug fixes, but I could not test them since now my server crashes even before I get the webpage open... So could someone else test the changes? In case I broke something we can return to the earlier versions of hakukone.py and index.html.

I will now try to reboot my computer if the crashing would be solved that simply :D

**Comment by kanerv** [comment]
I tested this and my python crashes when I do a search. If we cannot figure this out on our own, I have time tomorrow to attend Raul's extra session, so I can ask him what to do.

**Comment by TuukkaOT** [comment]
Have you tried with raul's demo that it works on your computer? Maybe there's a problem with a package or something, since the search works fine for me.

**Comment by saanahyttinen** [comment]
I tried Raul's demo and it works for me, the problem emerges only when I try to do a search on our app... Since it's happening to me and Kanerva but not Tuukka, could it be somehow mac-related...? I can also attend Raul's session tonight, maybe he could help us with this.

**Comment by saanahyttinen** [comment]
We were missing the line mlp.use('Agg') from our program and this solved the crashing for me at least! @kanerv let me know if it now works for you too!

**Comment by kanerv** [comment]
> We were missing the line mlp.use('Agg') from our program and this solved the crashing for me at least! @kanerv let me know if it now works for you too!

YES! I just pulled your changes and the app works now! Thank you Saana! 💪
