### ISSUE TITLE
[S] Come up with a name for the search engine

### ISSUE THREAD

**Issue by TuukkaOT** [kanerv/TuukkaSaanaKanerva#48]
We should have a good name for the engine, right? Any suggestions?
When I deleted the "TuukkaSaanaKanerva's...", I put "Rotten Linguist's search engine" on the title. I am definitely not married to that name, but it can be my first suggestion.

**Comment by kanerv** [comment]
I kinda like the rotten linguists 😆 🍅

**Comment by saanahyttinen** [comment]
I like it too :D
