### ISSUE TITLE
[M] Limit amount of adjectives/verbs listed in the plots

### ISSUE THREAD

**Issue by TuukkaOT** [kanerv/TuukkaSaanaKanerva#49]
Maybe top 10 most frequent? Lableled as [M] because I'm not sure if this is super easy or a little challenging.

**Comment by kanerv** [comment]
I turned the adjective plot into a pie chart. If there is less than 10 adjectives, the program plots all of them. If there is more, the program will rank the top 9 nine adjectives and sum the rest as "Other".

I commented the verb plot out for now. We can eventually delete the generate_verb_plot() function when we have something to replace it.

**Comment by kanerv** [comment]
The titles in the pie chart don't work properly with all queries. Seems like the labels possibly "cover" the title in some cases. Weird.... 🤔

**Comment by TuukkaOT** [comment]
Do you think it would be possible make it not include the query in the adjectives? Right now when you search, e.g., "strong", strong is 50% in the pie chart because all of the results contain that adjective.

**Comment by kanerv** [comment]
> Do you think it would be possible make it not include the query in the adjectives? Right now when you search, e.g., "strong", strong is 50% in the pie chart because all of the results contain that adjective.

Sure, but wouldn't users expect to see the query in the adjective's pie chart if the query itself is an adjective? I don't see the problem having it on the pie chart
