### ISSUE TITLE
[M] New refined search options

### ISSUE THREAD

**Issue by TuukkaOT** [kanerv/TuukkaSaanaKanerva#52]
More complex wildcard searches, Boolean, etc.

**Comment by kanerv** [comment]
I had an idea for the multiword search. Sadly it did not work yet... I left the button etc. in case the code comes to me in my dreams 🤞😄

**Comment by saanahyttinen** [comment]
> I had an idea for the multiword search. Sadly it did not work yet... I left the button etc. in case the code comes to me in my dreams 🤞😄

Nice! In case we get the multiword search working, let's remember to add the choice button also to indexnoresults.html! :)

**Comment by kanerv** [comment]
I gave up with the multiword search, so I deleted everything related to it from flask_relevance_search.py and index files
