### ISSUE TITLE
[S] Add intro text to search

### ISSUE THREAD

**Issue by TuukkaOT** [kanerv/TuukkaSaanaKanerva#53]

**Comment by saanahyttinen** [comment]
I added a small intro text with alink to the rotten tomatoes website. Feel free to add more ore change it, but remember to do the changes to both index.html and indexempty.html!

**Comment by saanahyttinen** [comment]
I tried to add a little tomato picture to the indexempty.html, but for some reason I'm not seeing it on the web interface. (my Finder preview shows it though) Let me know if it works for you! It is now on the starting page with no searches, if it works and we want to use it it we can add it also to index.html.

**Comment by saanahyttinen** [comment]
I just wanted to try if a picture works, so if you don't like this one we can find a better one!

**Comment by kanerv** [comment]
> I tried to add a little tomato picture to the indexempty.html, but for some reason I'm not seeing it on the web interface. (my Finder preview shows it though) Let me know if it works for you! It is now on the starting page with no searches, if it works and we want to use it it we can add it also to index.html.

Same here! I can't see it on my browser 😢 🍅 (But when I open indexempty.html with Finder, the tomato is there)

**Comment by kanerv** [comment]
I tried to get the tomato image to work in indexempty.html I had no luck, so I commented the part out for now and added some tomato emojis to both indexempty.html and index.html. Feel free to get rid of them if you don't like the look! 🍅

**Comment by saanahyttinen** [comment]
> I tried to get the tomato image to work in indexempty.html I had no luck, so I commented the part out for now and added some tomato emojis to both indexempty.html and index.html. Feel free to get rid of them if you don't like the look! 🍅

The emoji is a good idea! I added it also to indexnoresults.html
