### ISSUE TITLE
[M] Improve results printing layout.

### ISSUE THREAD

**Issue by TuukkaOT** [kanerv/TuukkaSaanaKanerva#54]

**Comment by saanahyttinen** [comment]
I changed the color of the bars in the theme plot from green to red, but for some reason I still get green bars for some of the searches...

**Comment by saanahyttinen** [comment]
> I changed the color of the bars in the theme plot from green to red, but for some reason I still get green bars for some of the searches...

I think the green plots are not an issue anymore!

**Comment by kanerv** [comment]
@saanahyttinen and @TuukkaOT what do you think about the emojis? Are they fine or does someone want to try the pictures still? I was just wondering if we could delete the commented html about the pictures 🍅

**Comment by saanahyttinen** [comment]
> @saanahyttinen and @TuukkaOT what do you think about the emojis? Are they fine or does someone want to try the pictures still? I was just wondering if we could delete the commented html about the pictures 🍅

I think the emoji looks good so no need for pictures necessarily!

**Comment by kanerv** [comment]
I changed the line _There are x **documents** matching your query x:_ as _There are x **movies** matching your query x:_ 

Also edited the theme plot title to match the others.

**Comment by saanahyttinen** [comment]
> I changed the line _There are x **documents** matching your query x:_ as _There are x **movies** matching your query x:_
> 
> Also edited the theme plot title to match the others.

I did the same for the line 'The score of act is 0.2129 in the _movie_ named:'
