### ISSUE TITLE
[S] Get rid of "mv_title" tags from search results

### ISSUE THREAD

**Issue by TuukkaOT** [kanerv/TuukkaSaanaKanerva#55]
If you search e.g. "great", 8.3% in the pie chart is "mv_title". It also shows in the themes graph sometimes. I'm not sure why this happens but there is probably some issue with how I made the tagging in the .txt file. We probably need to implement a re.sub or change the tagging in the data.

**Comment by kanerv** [comment]
<img width="1424" alt="Screenshot 2021-02-25 at 17 55 21" src="https://user-images.githubusercontent.com/77584213/109179552-b1fcd700-7792-11eb-95bb-13ba369d5844.png">

Yeah, I found a similar issue with a hyphen... It takes up the majority of _most frequent adjectives_ pie chart 🤔

**Comment by kanerv** [comment]
I found the bug! 🐛  There should not be mv_titles anymore in plots. However, there are quite a bit of **--** (double-hyphens? dashes?) in our data. Could we re-sub these as single hyphens? I wonder if this would help spacy to not tag the extra hyphens/dashes as adjectives?

**Comment by kanerv** [comment]
I added an if clause to the generate_adj_plot() that skips single character "adjectives" to avoid hyphens ending up to plots. Not the best solution, but I think it's good enough avoiding mistakes made by SpaCy.
