### ISSUE TITLE
[M] Fix app crashing when there are too many results

### ISSUE THREAD

**Issue by TuukkaOT** [kanerv/TuukkaSaanaKanerva#58]
If you search e.g. wildcard with "o", the app crashes with message "index out of range".

**Comment by saanahyttinen** [comment]
Fixed this with a try-except in the relevance_search(). The error message "There was a problem with the search" is vague but the program doesn't seemt to have to go there at all now. So no crashing at least! :)

**Comment by kanerv** [comment]
I tested wildcard searches for _of_ and _a_, and the program works fine, even thought here are 490 matches for the wildcard query _a_! 🎉  I think we can close this issue! 🙂
