### ISSUE TITLE
[M] Plots won't refresh between exact and wildcard when using the same query

### ISSUE THREAD

**Issue by kanerv** [kanerv/TuukkaSaanaKanerva#60]
I've been testing our app with '_act_', using both exact and wildcard searches. I've done a lot of test printing in the command line and I'm quite confident that our program does generate a new plot every time. However, it won't refresh in the user interface if the search term is the same, but the type of search is changed.

**Comment by kanerv** [comment]
I've no idea why this happens. If we can't figure this out by Monday, I can go and ask Raul...

**Comment by saanahyttinen** [comment]
Hmm... I wonder if the problem could somehow be in the fact that the name of the new plot the program generates is the same as the name of the previous plot in this case? And the old plot doesn't get overridden? This is just a guess though.

**Comment by kanerv** [comment]
> Hmm... I wonder if the problem could somehow be in the fact that the name of the new plot the program generates is the same as the name of the previous plot in this case? And the old plot doesn't get overridden? This is just a guess though.

I wondered about the same, but if the user enters a completely new query, the plots refresh as they should. So I'm not sure how that's possible since those plots are also saved under the same name... This whole thing doesn't make sense to me 💭

**Comment by saanahyttinen** [comment]
> > Hmm... I wonder if the problem could somehow be in the fact that the name of the new plot the program generates is the same as the name of the previous plot in this case? And the old plot doesn't get overridden? This is just a guess though.
> 
> I wondered about the same, but if the user enters a completely new query, the plots refresh as they should. So I'm not sure how that's possible since those plots are also saved under the same name... This whole thing doesn't make sense to me 

Yeah but when the query word is different than the previous query, the name of the plot picture changes since it takes the query as a part of the name, like e.g. adj_woman_plot_pie.png to adj_man_plot_pie.png. But when the query is the same word as the previous query the name of the plot picture is identical to what it was... But I really don't know if this could be the reason for it not refreshing...

**Comment by kanerv** [comment]
> > > Hmm... I wonder if the problem could somehow be in the fact that the name of the new plot the program generates is the same as the name of the previous plot in this case? And the old plot doesn't get overridden? This is just a guess though.
> > 
> > 
> > I wondered about the same, but if the user enters a completely new query, the plots refresh as they should. So I'm not sure how that's possible since those plots are also saved under the same name... This whole thing doesn't make sense to me
> 
> Yeah but when the query word is different than the previous query, the name of the plot picture changes since it takes the query as a part of the name, like e.g. adj_woman_plot_pie.png to adj_man_plot_pie.png. But when the query is the same word as the previous query the name of the plot picture is identical to what it was... But I really don't know if this could be the reason for it not refreshing...

This worked! Thank you @saanahyttinen !!!! 😀 
I had to move the _extractor()_ function out of _relevance_search()_, to the if-strands in _search()_, but I think there should be no bugs 🐛
