### ISSUE TITLE
[M] Add a plot

### ISSUE THREAD

**Issue by saanahyttinen** [kanerv/TuukkaSaanaKanerva#62]
If we want to have three plots, let's add another plot

**Comment by kanerv** [comment]
I was looking at our ner highlights and I'm not sure if it is a good idea to turn ners into a plot after all... Spacy doesn't recognize the names of the movies too well (or consistently), since sometimes they are a _work of art_, and sometimes _people_ or _organizations_ etc.

Should we consider PoS tags? I'm not sure if it's terribly interesting to see e.g., how much determiners, etc. are used in movie reviews specifically, but that would be something we haven't implemented yet and I think knowing how to extract PoS tags would likely be useful for other projects?

Or we can also just roll with the verbs! I'm open to ideas!

**Comment by saanahyttinen** [comment]
> I was looking at our ner highlights and I'm not sure if it is a good idea to turn ners into a plot after all... Spacy doesn't recognize the names of the movies too well (or consistently), since sometimes they are a _work of art_, and sometimes _people_ or _organizations_ etc.
> 
> Should we consider PoS tags? I'm not sure if that's terribly interesting to see e.g., how much determiners etc are used in movie reviews specifically, but that would be something we haven't implemented yet and a skill that would likely be useful for other projects?
> 
> Or we also just roll with the verbs! I'm open to ideas!

I returned the query distribution by documents, because I thought it might actually be interesting to see. I'm just trying to push my changes but having some merging issues :)

I did try to get something out of the NER persons etc but also came to the conclusion that I don't really know what interesting they could offer and it turned out to be quite a lot of work to get all of the information out...

PoS would be another interesting option though!
EDIT: And I'm fine with the verb plot too!

**Comment by kanerv** [comment]
> > I was looking at our ner highlights and I'm not sure if it is a good idea to turn ners into a plot after all... Spacy doesn't recognize the names of the movies too well (or consistently), since sometimes they are a _work of art_, and sometimes _people_ or _organizations_ etc.
> > Should we consider PoS tags? I'm not sure if that's terribly interesting to see e.g., how much determiners etc are used in movie reviews specifically, but that would be something we haven't implemented yet and a skill that would likely be useful for other projects?
> > Or we also just roll with the verbs! I'm open to ideas!
> 
> I returned the query distribution by documents, because I thought it might actually be interesting to see. I'm just trying to push my changes but having some merging issues :)
> 
> I did try to get something out of the NER persons etc but also came to the conclusion that I don't really know what interesting they could offer and it turned out to be quite a lot of work to get all of the information out...
> 
> PoS would be another interesting option though!
> EDIT: And I'm fine with the verb plot too!

I'm not sure if _query distribution_ really describes the plot? If I understood it right, the plot tracks the lenght  (i.e. how many words) of each critic consensus that match the search. So maybe _total word distribution_ was better? Or just _content lenght_?

**Comment by kanerv** [comment]
I created a bar plot that tracks the Part-of-Speech tag distribution. I also turned the verb plot into a pie chart. I still think three plots are enough, but now do test searches and decide what charts we want to keep! 🙂

**Comment by saanahyttinen** [comment]
> 
> I'm not sure if _query distribution_ really describes the plot? If I understood it right, the plot tracks the lenght (i.e. how many words) of each critic consensus that match the search. So maybe _total word distribution_ was better? Or just _content lenght_?

I think you're right, I've understood the plot wrong myself! I tried to do one where you could see which reviews are the matching ones and which match the query best. In that case it's not very interesting and I'm totally fine with removing it! :D

I did some testing and I think maybe the verb plot would be the most interesting in addition to the adjective and the theme plot. Especially when searching with nouns it's actually quite nice to see what verbs they are used together with.
The PoS distribution is cool too, but I noticed I was more interested in looking at the verbs when doing searches. Keeping which ever is fine for me though. :)

**Comment by saanahyttinen** [comment]
I went on and removed the "distribution" plot already!

**Comment by kanerv** [comment]
I quite like the PoS plot in addition to the verbs and adjectives, since now you can also see how many verbs and adjectives there are in total (which is not apparent from the pie charts). Would four charts be a bad idea? 😅

**Comment by kanerv** [comment]
Well, the four plots don't look as nice as the three, but what do you think @saanahyttinen @TuukkaOT?

**Comment by TuukkaOT** [comment]
I think these are all pretty interesting. Right now they look a bit lonely because they're so small and sparsely located on the screen. If we make the plots larger and tweak their positioning, padding etc. I think it could look pretty nice in a 2x2 grid.

**Comment by saanahyttinen** [comment]
Yeah I think four plots can work too!

**Comment by kanerv** [comment]
> > I'm not sure if _query distribution_ really describes the plot? If I understood it right, the plot tracks the lenght (i.e. how many words) of each critic consensus that match the search. So maybe _total word distribution_ was better? Or just _content lenght_?
> 
> I think you're right, I've understood the plot wrong myself! I tried to do one where you could see which reviews are the matching ones and which match the query best. In that case it's not very interesting and I'm totally fine with removing it! :D
> 
> I did some testing and I think maybe the verb plot would be the most interesting in addition to the adjective and the theme plot. Especially when searching with nouns it's actually quite nice to see what verbs they are used together with.
> The PoS distribution is cool too, but I noticed I was more interested in looking at the verbs when doing searches. Keeping which ever is fine for me though. :)

Hey, @saanahyttinen I think we could have done your query plot by using the `score` form `ranked_scores_and_doc_ids`! Instead of having `dist_dict1[match['name']] = len(match['content']` we would need to feed the scores as `dist_dict`values. This would then show the most "matching" document as the highest score etc. Of course the printed documents already are ranked when printed in UI, but sure the "best match" would become more obvious from a plot.

EDIT: Although we still would have the issue of having too many documents in one plot... But then we would just need to limit them to top something maybe...

**Comment by saanahyttinen** [comment]
> > > I'm not sure if _query distribution_ really describes the plot? If I understood it right, the plot tracks the lenght (i.e. how many words) of each critic consensus that match the search. So maybe _total word distribution_ was better? Or just _content lenght_?
> > 
> > 
> > I think you're right, I've understood the plot wrong myself! I tried to do one where you could see which reviews are the matching ones and which match the query best. In that case it's not very interesting and I'm totally fine with removing it! :D
> > I did some testing and I think maybe the verb plot would be the most interesting in addition to the adjective and the theme plot. Especially when searching with nouns it's actually quite nice to see what verbs they are used together with.
> > The PoS distribution is cool too, but I noticed I was more interested in looking at the verbs when doing searches. Keeping which ever is fine for me though. :)
> 
> Hey, @saanahyttinen I think we could have done your query plot by using the `score` form `ranked_scores_and_doc_ids`! Instead of having `dist_dict1[match['name']] = len(match['content']` we would need to feed the scores as `dist_dict`values. This would then show the most "matching" document as the highest score etc. Of course the printed documents already are ranked when printed in UI, but sure the "best match" would become more obvious from a plot.
> 
> EDIT: Although we still would have the issue of having too many documents in one plot... But then we would just need to limit them to top something maybe...

Yeah, true!! That would probably have worked! But maybe the ranking of the printed results is enough since we already have quite many plots. :)
