### ISSUE TITLE
[S] Last thing to do: clean the code from unnecessary comments, lines, etc.

### ISSUE THREAD

**Issue by kanerv** [kanerv/TuukkaSaanaKanerva#64]
Finishing touches! 🎉

**Comment by saanahyttinen** [comment]
Line 171  '#keyphrases_str = '\n'.join(str(v) for v in keyphrases)'  is commented out atm, was it just for printing the keyphrases and should we remove it?

Otherwise I think we don't have any code commented out anymore, just actual comments!

**Comment by kanerv** [comment]
> Line 171 '#keyphrases_str = '\n'.join(str(v) for v in keyphrases)' is commented out atm, was it just for printing the keyphrases and should we remove it?
> 
> Otherwise I think we don't have any code commented out anymore, just actual comments!

Oh yeah! I forgot to ask about those! `keyphrases_str`was for printing, so we don't need that anymore and the few commented lines in `generate_theme_plot()` were probably leftovers from an old scatterplot or something? @TuukkaOT can correct me if I'm wrong, but I think all that can be deleted 🙂

**Comment by kanerv** [comment]
I forgot to tag my last commit here, but I deleted those commented code lines and also got rid of the importing of modules we did not end up using
