### ISSUE TITLE
[S] Improve instructions on README.md if needed to be more specific

### ISSUE THREAD

**Issue by saanahyttinen** [kanerv/TuukkaSaanaKanerva#66]
If we need to give more specific instructions on how to use our program, we could update them on the README.md.

**Comment by saanahyttinen** [comment]
Should we list for example what modules etc. need to be installed for the program to run?

**Comment by saanahyttinen** [comment]
> Should we list for example what modules etc. need to be installed for the program to run?

Nevermind, I noticed it was already there! :)
Is there anything else you guys think we should add to the instructions?

**Comment by TuukkaOT** [comment]
Yeh sorry I made the changes but forgot to refer to an issue :) I don't know if there's anything else to add really.
